genome: /user/work/tk19812/AntSpringtail/Genomes/Cant0000001.assembly.v1.0.fasta
outdir: /user/work/tk19812/AntSpringtail/CantScf01TEannotation
species: CantScf01
threads: 16
preset: Collembola

repeatmodeler_dir: /user/work/tk19812/software/RepeatModeler-2.0.4
repeatscout_dir: /user/work/tk19812/software/RepeatScout
repeatmasker_bin: /user/work/tk19812/software/RepeatMasker/RepeatMasker
repeatmodeler_extend_script: /user/work/tk19812/software/RepeatModeler-2.0.4/util/davidExtendConsRAM.pl
repeatclassifier_bin: RepeatClassifier
ucsc_tools_dir: /user/work/tk19812/software/Kent/bin/x86_64
repeat_after_me_dir: /user/work/tk19812/software/RepeatAfterMe
phrap_dir: /user/work/tk19812/software/phrap

repeatpeps_db_dir: /user/work/tk19812/software/RepeatMasker/Libraries/
diamond_bin: diamond
getorf_bin: getorf
cdhit_est_bin: cd-hit-est

cdhit_identity: 0.95
extension_max_hits: 50
extension_left_buffer: 100
extension_right_buffer: 100
min_orf: 500
