RT:
  aliases:
    - RT
    - RT_domain
    - RVT
    - RVT_1
    - RVT_2
    - Reverse_transcriptase
    - Reverse-transcriptase
    - retropepsin
  order: RETRO

INTEGRASE:
  aliases:
    - INT
    - INT_domain
    - Integrase
    - Retroviral_integrase
    - rve
  order: LTR

RNASEH:
  aliases:
    - RNaseH
    - RNase_H
    - RH
    - RH_domain
  order: RETRO

GAG:
  aliases:
    - GAG
    - Gag
    - gag
  order: LTR

ENV:
  aliases:
    - ENV
    - Env
    - envelope
  order: RETRO

TRANSPOSASE:
  aliases:
    - Transposase
    - Transposase_domain
    - DDE
    - DDE_Tnp
    - DDE_Tnp_1
    - hAT
    - Tc1
    - Mariner
    - Mutator
    - PIF
  order: TIR

PIGGYBAC:
  aliases:
    - PiggyBac
    - piggyBac
  order: TIR
  superfamily: PiggyBac

MUTATOR:
  aliases:
    - MULE
    - Mutator
  order: TIR
  superfamily: Mutator

PIF_HARBINGER:
  aliases:
    - PIF
    - Harbinger
  order: TIR
  superfamily: PIF-Harbinger

TCMAR:
  aliases:
    - Tc1
    - Mariner
    - TcMar
    - Transposase_21
    - HTH_Tnp_Tc5
  order: TIR
  superfamily: TcMar

HELITRON_REP:
  aliases:
    - Helitron
    - RepHel
    - Replicase
    - Rolling_circle
  order: Helitron
  superfamily: Helitron

HELICASE:
  aliases:
    - Helicase
    - DEXDc
    - HELICc
  order: Helitron
